### ISSUE TITLE
[feature Request] Linux support?

### ISSUE THREAD

**Issue by Greyhash-dev** [Niravk1997/HP-Agilent-Keysight-34401A-Control-and-Data-Logging-Software#1]
Hello,
I wanted to ask if there is a way to add linux support?
That would be awsome!
Thanks!

**Comment by Niravk1997** [comment]
Short Answer: No.
Long Answer: You can switch the GUI framework from WPF to Avalonia but nobody has time for that.
Hope this helps.

**Comment by Niravk1997** [comment]
Try this software, it works with Linux.
https://www.eevblog.com/forum/testgear/program-that-can-log-from-many-multimeters/

**Comment by Greyhash-dev** [comment]
Thanks for your help! (:
