### ISSUE TITLE
Crash on populating the List of GPIB Ports

### ISSUE THREAD

**Issue by i3v** [Niravk1997/HP-Agilent-Keysight-34401A-Control-and-Data-Logging-Software#3]
This crash, is most likely a result of my own ignorance (most probably, I've not rebooted my PC after NI/KeySight software installation). But that's still a crash... Also, maybe someone else would run into it as well.

I've just installed the binary release [HP_34401A_Software_VISA_GPIB.zip](https://github.com/Niravk1997/HP-Agilent-Keysight-34401A-Control-and-Data-Logging-Software/releases/download/1.0.0/HP_34401A_Software_VISA_GPIB.zip) on a PC without any NI/Agilent software previously installed. Only freshly installed `ni-488.2_20.0.0_offline.iso` and `IOLibSuite_18_2_27115.exe` (2021 Update1).

The app started OK, but crashed in about a second after clicking "Config->Connect". For a very short while, an empty device list and  error messages "Failed to find resources matching GPIB?*" + "Failed to get list of GPIB devices" have been displayed:
![crashes](https://github.com/Niravk1997/HP-Agilent-Keysight-34401A-Control-and-Data-Logging-Software/assets/920364/8c1f0224-a038-438d-9304-2daba5e67629)

In the Windows Event viewer, two error messages are logged:
EventID=1000

1. 
```
Faulting application name: HP 34401A.exe, version: 1.0.0.0, time stamp: 0x9c73fe42
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2846, time stamp: 0xb9bbdd8b
Exception code: 0xe0434352
Fault offset: 0x00138fc2
Faulting process id: 0x3184
Faulting application start time: 0x01d98e599f52349b
Faulting application path: C:\ProgramFiles_rw\Agilent_34401A_Software_VISA_GPIB\HP 34401A.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 5b2fb719-ec20-4047-b658-0d87add1aab7
Faulting package full name: 
Faulting package-relative application ID: 
```
   * same on another similar PC:
```
Faulting application name: HP 34401A.exe, version: 1.0.0.0, time stamp: 0x9c73fe42
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1766, time stamp: 0x270baf18
Exception code: 0xe0434352
Fault offset: 0x0012c3a2
Faulting process id: 0x380c
Faulting application start time: 0x01d98e6fecfddd88
Faulting application path: C:\ProgramFiles_rw\Agilent_34401A_Software_VISA_GPIB\HP 34401A.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 40eaa7dc-de19-4b14-9122-032490f5e149
Faulting package full name: 
Faulting package-relative application ID: 
```

2. 
    Immediately followed by EventID = 1026
```
Application: HP 34401A.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
   at Keysight.Visa.NativeWrapper+NativeMethods.Close(UInt32)
   at Keysight.Visa.NativeWrapper.Close(UInt32)
   at Keysight.Visa.ResourceManager.Dispose(Boolean)
   at Keysight.Visa.ResourceManager.Finalize()
```

After rebooting twice (I guess this is what helped, but I'm not 100% sure) the issue is gone, and now the same dialog window shows "GPIB0::INTFC" and "GPIB0::22::INSTR,". 
![image](https://github.com/Niravk1997/HP-Agilent-Keysight-34401A-Control-and-Data-Logging-Software/assets/920364/8a558c33-3590-4136-beed-1477deb9656b)
And the software works great. :)

**Comment by Niravk1997** [comment]
Not a bug.
