### ISSUE TITLE
Provide more baud options to work with Galvant GPIBUSB

### ISSUE THREAD

**Issue by orion3311** [Niravk1997/HP-Agilent-Keysight-34401A-Control-and-Data-Logging-Software#4]
Just wondering if it would be possible to add more baud options up to 460800 to work with the Galvant GPIBUSB adapter? http://www.galvant.ca/#!/store/gpibusb

Alternatively I may see if I can recompile the firmware for it to dial the baud rate down a bit, since it's hard coded and doesn't have autodetect its stuck at 460800. 

App looks awesome - hoping I can make it work with this. All the commands appear to be compatible so just a baud rate change should work.

**Comment by Niravk1997** [comment]
Yes, super easy. In the COM_Select_Window.xaml file add line similar to this ComboBoxItem Content="128000" IsSelected="False" IsEnabled="True" but change the 128000 value to 460800.

**Comment by orion3311** [comment]
I'm afraid I don't see that file - this is all I see when I unzip the files. I did try setting the serial config file to that baud, but it doesn't work.

![Capture1](https://github.com/Niravk1997/HP-Agilent-Keysight-34401A-Control-and-Data-Logging-Software/assets/23561199/a973450b-7961-4a31-82d0-69876d22542d)

**Comment by Niravk1997** [comment]
I was talking about the source code file. Here it is (https://github.com/Niravk1997/HP-Agilent-Keysight-34401A-Control-and-Data-Logging-Software/blob/main/src/Old_Versions/HP%2034401A%20(AR488%20Arduino%20GPIB)/COM_Select_Window.xaml), around line 70. You will need visual studio 2019 community version with desktop application development addon to compile the source code.
